# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aJ0Kgl8Tq4qA71ZKwxxdTxBok9GLYrQ2
"""

# Commented out IPython magic to ensure Python compatibility.
#!git clone https://github.com/JordanFoss/STAT3007_Project.git
# %cd STAT3007_Project/



import numpy as np
import librosa
from librosa.effects import split
import matplotlib.pyplot as plt
import glob
from torch.utils.data import DataLoader, Dataset, random_split
import torch

from pre_process import *

def load_noisy_samples(model_folder):
    # load samples
    X = []
    y = []
    
    for gender_folder in glob.glob(model_folder + '/*'):
        for actor_folder in glob.glob(gender_folder + '/*'):
            for sample_path in glob.glob(actor_folder + '/*.wav'):
              
              sample_name = sample_path.split('/')[-1]
              
              emotion, intensity, repetition, statement, actor = tuple(sample_name.split('-')[:5])

              sample, sampling_rate = librosa.load(sample_path, sr = 16000)
              mel_spectrogram = data_gen(sample, sampling_rate ,2)
              
              target = target_generation(sample_name)
        
              X.append(mel_spectrogram)
              y.append(target)
    
    return X, y

class DatasetWrapper(Dataset):
      def __init__(self, X, y):
          self.X, self.y = X, y
    
      def __len__(self):
          return len(self.X)
    
      def __getitem__(self, idx):
          return self.X[idx], self.y[idx]
      
      def change_type(self, dtype):
    
          return DatasetWrapper(self.X.type(dtype),self.y.type(dtype))
      
      def dataset(self):
          return DatasetWrapper(self.X,self.y)
      
      def get_data(self):
          return self.X, self.y


def train_test_gen(X,y, train_ratio = 0.7, seed = 10):
    '''
    Generates training/test datasets

    Parameters
    ----------
    X : list
        list of mel-spectrograms
    y : list
        list of emotion labels
    train_ratio : float, optional
        ratio of samples for training. The default is 0.7.
    seed : int, optional
        random generator seed. The default is 10.

    Returns
    -------
    data_test : Dataset.Subset
        test dataset
    data_train : Dataset.Subset
        train dataset

    '''
    X = torch.tensor(X)
    X = X.reshape(X.shape[0],1,X.shape[1],X.shape[2])
    y = torch.tensor(y)
      
    data = DatasetWrapper(X,y)
    train_size = int(X.shape[0] * train_ratio)
    test_size = X.shape[0] - train_size
      
    data_test, data_train = random_split(data,[test_size,train_size], generator = torch.Generator().manual_seed(seed))
      
    return data_test, data_train


def load_sets(X,y,train_ratio = [0.7,0.7], seed = [10,11]):
    '''
    Loading training and test sets. It has the option to split up to twice

    Parameters
    ----------
    X : list
        list of mel-spectrograms
    y : list
        emotion labels
    train_ratio : list, optional
        train_ratios of first and second split. The default is [0.7,0.7].
    seed : list, optional
        random seeds for first and second split. The default is [10,11].

    Returns
    -------
    data_sets : list
        list of train_test split subsets

    '''
    data_sets = []
    for i in range(len(train_ratio)):
        data_test, data_train = train_test_gen(X,y, train_ratio[0], seed[0])
        data_sets.append((data_train,data_test))
        X,y = data_test.dataset.get_data()
        
    return data_sets
        
        
        

